; Generated by ez80-clang
;	section	.text
;	public	_draw_lives_c
;_draw_lives_c:
;	ld	hl, 29
;	ld	de, 164
;	push	de
;	push	hl
;	call	_gfx_SetTextXY
;	pop	hl
;	pop	hl
;	ld	a, (_oiram+38)
;	or	a, a
;	sbc	hl, hl
;	ld	l, a
;	ld	de, 2
;	push	de
;	push	hl
;	call	_gfx_PrintUInt
;	pop	hl
;	pop	hl
;	ld	hl, 8
;	push	hl
;	ld	hl, -92
;	push	hl
;	ld	hl, 1
;	push	hl
;	call	_gfx_BlitLines
;	pop	hl
;	pop	hl
;	pop	hl
;	ret

; Edited version that saves 7 bytes, but uses slightly more stack
	section	.text
	public	_draw_lives
_draw_lives:
	ld	hl, 164
	push	hl
	ld	l, 29
	push	hl
	call	_gfx_SetTextXY
	ld	hl, 2
	push	hl
	ld	a, (_oiram+38)
	ld	l, a
	push	hl
	call	_gfx_PrintUInt
	ld	hl, 8
	push	hl
	ld	l, 164
	push	hl
	ld	l, 1		; _gfx_buffer
	push	hl
	call	_gfx_BlitLines
	ld	hl, 21
	add	hl, sp
	ld	sp, hl
	ret

	extern	_oiram
	extern	_gfx_PrintUInt
	extern	_gfx_BlitLines
	extern	_gfx_SetTextXY
